import { StoriesSchema, type Story } from './schemas';

const data: Story[] = [
  {
    t: 'رحلة إلى لندن',
    lines: [
      'Faisal had always dreamed of visiting London.',
      'He booked his flight and hotel online by himself.',
      'At the airport, he asked for directions in English.',
      'Excuse me, which gate is for the London flight?',
      'The flight attendant smiled and pointed the way.',
      'In London, he took the underground to his hotel.',
      'He ordered fish and chips at a local restaurant.',
      'The waiter asked, Would you like anything to drink?',
      'Just water, please, Faisal replied with confidence.',
      'He realized his English was better than he thought.',
    ],
  },
  {
    t: 'عند الدكتور',
    lines: [
      'Huda moved to a new city and needed a doctor.',
      'She called the clinic to book an appointment.',
      'I would like to see a doctor this week, she said.',
      'The receptionist asked about her symptoms.',
      'I have had a headache for three days, Huda explained.',
      'The doctor examined her carefully and asked questions.',
      'Have you been under a lot of stress recently?',
      'Yes, I just moved and started a new routine.',
      'The doctor recommended rest and staying hydrated.',
      'Huda left feeling relieved and understood.',
    ],
  },
  {
    t: 'اجتماع أولياء الأمور',
    lines: [
      "Tariq went to his daughter's school for a meeting.",
      'The teacher greeted him in English warmly.',
      'Thank you for coming. Sara is a wonderful student.',
      'She is very good at math but needs help with reading.',
      'Tariq listened carefully and took mental notes.',
      'What can I do at home to help her, he asked.',
      'Read with her for fifteen minutes every night.',
      'That sounds simple enough, Tariq said.',
      'He felt proud that he understood the whole conversation.',
      'On the way home, he started planning their reading time.',
    ],
  },
  {
    t: 'التسوق أونلاين',
    lines: [
      'Mona wanted to buy a laptop from an international store.',
      'She compared prices and read reviews in English.',
      'This one has great battery life, one review said.',
      'She added it to her cart and went to checkout.',
      'The website asked for her shipping address.',
      'She typed everything carefully in English.',
      'A chat window popped up asking if she needed help.',
      'Yes, does this ship to Saudi Arabia, she typed.',
      'The agent confirmed and gave her a tracking number.',
      'The laptop arrived in perfect condition a week later.',
    ],
  },
  {
    t: 'مقابلة العمل',
    lines: [
      'Ahmed prepared carefully for his interview.',
      'He reviewed the company website and recent news.',
      'Tell me about yourself, the interviewer began.',
      'Ahmed spoke about his ten years of experience.',
      'He mentioned specific projects he was proud of.',
      'The interviewer was impressed by his preparation.',
      'What motivates you in your career, she asked.',
      'Solving problems and helping my team grow, he said.',
      'Both sides felt the interview went very well.',
      'Ahmed received an offer the following week.',
    ],
  },
  {
    t: 'في المطعم',
    lines: [
      'Salma and her husband went to a nice restaurant.',
      'Good evening. A table for two, please, she said.',
      'The waiter brought the menu and explained the specials.',
      'Tonight we have grilled salmon with lemon sauce.',
      'That sounds delicious. I will have that, Salma said.',
      'Her husband ordered a steak, medium well.',
      'They enjoyed their meal and had a great conversation.',
      'Could we have the dessert menu, please, she asked.',
      'They shared a chocolate cake and drank coffee.',
      'The evening was perfect from start to finish.',
    ],
  },
  {
    t: 'الجار الجديد',
    lines: [
      'A new family moved in next door to Youssef.',
      'He decided to welcome them with a friendly visit.',
      'Hi, I am Youssef. Welcome to the neighborhood.',
      'The neighbor smiled and introduced his family.',
      'We just moved from Canada, the neighbor explained.',
      'If you need anything, please do not hesitate to ask.',
      'They talked about the best schools and grocery stores.',
      'Youssef recommended his favorite local restaurant.',
      'They exchanged phone numbers before saying goodbye.',
      'A simple conversation turned into a real friendship.',
    ],
  },
  {
    t: 'أول يوم في الدورة',
    lines: [
      'Layla signed up for an online photography course.',
      'The instructor spoke English with a British accent.',
      'Welcome everyone. Let me introduce myself first.',
      'She took notes in English for the first time.',
      'Today we will learn about lighting and composition.',
      'The instructor showed examples and asked for opinions.',
      'Layla typed in the chat, I think the second photo is better.',
      'Great observation, the instructor replied.',
      'She felt a rush of confidence after being noticed.',
      'By the end of the class, she had learned ten new words.',
    ],
  },
];

export const STORIES = StoriesSchema.parse(data);
